const fs = require('fs');
const path = require('path');

const frContent = {
  "heroSurtitre": "QUI SOMMES-NOUS",
  "heroTitle": "AFAQ HEALTH, partenaire du développement des marques de santé",
  "heroSubtitle": "De l’Europe au marché marocain, nous construisons les conditions d’une implantation durable.",
  "heroText1": "AFAQ HEALTH est une société marocaine spécialisée dans le développement, l’importation et la commercialisation de marques européennes dans les domaines de la nutrition, des compléments alimentaires et du bien-être.",
  "heroText2": "Nous accompagnons des fabricants et des marques européennes dans leur développement sur le marché marocain, en associant connaissance du marché local, exigence réglementaire, développement commercial et réseau professionnel.",
  "heroHighlight": "Notre rôle ne se limite pas à distribuer des produits. Nous construisons leur présence sur le marché.",
  
  "missionTitle": "NOTRE MISSION",
  "missionSubtitle": "Rendre accessibles des solutions européennes de qualité, avec une approche locale exigeante.",
  "missionText1": "Notre mission est de sélectionner et développer des marques répondant à des critères élevés de qualité, de formulation et de conformité, puis de créer les conditions nécessaires à leur développement durable sur le marché marocain.",
  "missionText2": "Nous intervenons à l’interface entre les fabricants européens et les différents acteurs de la chaîne de santé, en assurant la coordination nécessaire entre les exigences du fabricant, les contraintes du marché local et les besoins des professionnels.",
  "chainTitle": "CHAÎNE DE VALEUR",
  "chain1": "Fabricants européens",
  "chain2": "AFAQ HEALTH",
  "chain3": "DAWA MAGHREB — Distributeur national",
  "chain4": "Pharmacies",
  "chain5": "Consommateurs",
  "accompagnementTitle": "ACCOMPAGNEMENT DES PROFESSIONNELS DE SANTÉ",
  "accompagnement1": "AFAQ HEALTH → Professionnels de santé",
  "accompagnement2": "Conseil et information des consommateurs",
  "accompagnement3": "Le conseil délivré au consommateur relève du professionnel de santé, dans le cadre de son exercice.",
  "missionClosing": "Notre ambition est de construire des relations durables, fondées sur la confiance, la rigueur et une vision de long terme.",

  "expertiseSurtitre": "NOTRE POSITIONNEMENT & NOTRE EXPERTISE",
  "expertiseTitle": "Plus qu’un distributeur, un partenaire de développement.",
  "expertiseText1": "L’accès à un nouveau marché ne se résume pas à l’importation d’un produit.",
  "expertiseText2": "Il nécessite de comprendre son environnement réglementaire, d’adapter son positionnement, de préparer son lancement, de construire ses circuits de distribution et de développer progressivement sa présence auprès des professionnels de santé et des consommateurs.",
  "expertiseText3": "C’est précisément le rôle d’AFAQ HEALTH.",
  "expertiseSubtitle": "Une approche intégrée en six expertises",
  "exp1Title": "01 — ACCÈS AU MARCHÉ",
  "exp1Desc": "Analyse du potentiel, positionnement, segmentation et préparation du lancement sur le marché marocain.",
  "exp2Title": "02 — RÉGLEMENTATION & CONFORMITÉ",
  "exp2Desc": "Coordination des démarches réglementaires, préparation et suivi de la documentation produit, conformité des supports et suivi des exigences applicables.",
  "exp3Title": "03 — IMPORTATION & MISE À DISPOSITION",
  "exp3Desc": "Organisation des opérations d’importation et coordination avec les partenaires afin d’assurer la disponibilité des produits sur le marché.",
  "exp4Title": "04 — DÉVELOPPEMENT COMMERCIAL",
  "exp4Desc": "Construction et développement des circuits de distribution, accompagnement du lancement et développement progressif des gammes.",
  "exp5Title": "05 — ACCOMPAGNEMENT DES PROFESSIONNELS",
  "exp5Desc": "Mise à disposition d’informations produits et accompagnement des pharmaciens et professionnels de santé dans la connaissance des gammes et de leur utilisation.",
  "exp6Title": "06 — DÉVELOPPEMENT DE LA MARQUE",
  "exp6Desc": "Positionnement, supports marketing, communication et actions destinées à construire progressivement une présence durable sur le marché.",

  "reseauSurtitre": "NOTRE RÉSEAU",
  "reseauTitle": "Créer des passerelles entre les marques et les professionnels de santé",
  "reseauSubtitle": "Le développement d’une marque de santé repose sur la qualité de son environnement professionnel.",
  "reseauText": "AFAQ HEALTH travaille avec des partenaires complémentaires afin de créer une chaîne cohérente, de la mise à disposition des produits jusqu’à leur accès au consommateur.",
  "net1Title": "FABRICANTS EUROPÉENS",
  "net1Desc": "Des partenaires sélectionnés pour la qualité de leurs produits, leur savoir-faire et leur capacité à accompagner le développement de leurs marques sur de nouveaux marchés.",
  "net2Title": "DISTRIBUTEURS & GROSSISTES",
  "net2Desc": "Des partenaires permettant d’assurer une couverture commerciale et une disponibilité adaptées au marché. La distribution nationale des produits AFAQ HEALTH est assurée par DAWA MAGHREB, établissement pharmaceutique agréé.",
  "net3Title": "PHARMACIES",
  "net3Desc": "Le réseau officinal constitue un point de contact essentiel pour la mise à disposition des produits et leur accès aux consommateurs.",
  "net4Title": "PROFESSIONNELS DE SANTÉ",
  "net4Desc": "Une relation de proximité permettant de mieux présenter les caractéristiques des produits et de contribuer à une information adaptée des consommateurs.",
  "reseauClosing": "Notre objectif : construire autour de chaque marque un réseau cohérent et durable, plutôt qu’une simple chaîne de distribution.",

  "engagementsSurtitre": "NOS ENGAGEMENTS",
  "engagementsTitle": "Exigence. Conformité. Transparence. Responsabilité.",
  "eng1Title": "QUALITÉ",
  "eng1Desc": "Nous privilégions des marques et des produits répondant à des critères exigeants de qualité, de formulation et de traçabilité.",
  "eng2Title": "CONFORMITÉ",
  "eng2Desc": "Nous accordons une attention particulière aux exigences réglementaires applicables à chaque produit avant sa mise sur le marché et tout au long de son développement.",
  "eng3Title": "PARTENARIAT",
  "eng3Desc": "Nous privilégions des relations durables avec nos fabricants, distributeurs, pharmaciens et professionnels de santé.",
  "eng4Title": "RESPONSABILITÉ",
  "eng4Desc": "Nous veillons à développer nos marques avec une communication claire, responsable et adaptée au statut réglementaire de chaque produit.",

  "portefeuilleSurtitre": "NOTRE PORTEFEUILLE",
  "portefeuilleTitle": "Des marques européennes sélectionnées pour leur potentiel",
  "portefeuilleSubtitle": "AFAQ HEALTH développe progressivement un portefeuille de marques complémentaires dans les domaines de la nutrition, des compléments alimentaires et du bien-être.",
  "brand1Title": "SOTYA",
  "brand1Status": "Disponible au Maroc",
  "brand1Desc": "Une marque espagnole de compléments alimentaires développée autour de différentes catégories de nutrition et de bien-être.",
  "brand1Link": "Découvrir SOTYA",
  "brand2Title": "NATURAMINS KIDS",
  "brand2Status": "Lancement prévu en janvier 2027",
  "brand2Desc": "Une gamme dédiée à la nutrition et au bien-être de l’enfant.",
  "brand2Link": "Découvrir Naturamins Kids",
  "brand3Title": "COLAGENOVA",
  "brand3Status": "Prochain lancement",
  "brand3Desc": "Une gamme spécialisée dans les solutions à base de collagène, autour notamment de la beauté et de la mobilité.",
  "brand3Link": "Découvrir Colagenova",
  "allBrandsBtn": "Découvrir toutes nos marques",

  "ambitionSurtitre": "NOTRE AMBITION",
  "ambitionTitle": "Construire des marques durables sur les marchés africains.",
  "ambitionText1": "Le Maroc constitue notre marché de développement et notre point d’ancrage.",
  "ambitionText2": "À terme, AFAQ HEALTH souhaite accompagner certaines des marques de son portefeuille vers d’autres marchés d’Afrique francophone, en tenant compte des spécificités réglementaires, commerciales et professionnelles propres à chaque pays.",
  "ambitionText3": "Cette ambition repose sur une approche progressive : consolider d’abord les marques sur le marché marocain, puis construire, lorsque les conditions sont réunies, leur développement régional.",
  "ambitionHighlight": "Notre ambition n’est pas de multiplier les références. Elle est de construire un portefeuille cohérent de marques de santé, capables de s’inscrire durablement dans leurs marchés."
};

const enContent = {
  "heroSurtitre": "WHO WE ARE",
  "heroTitle": "AFAQ HEALTH, Partner in Healthcare Brand Development",
  "heroSubtitle": "From Europe to the Moroccan market, we build the conditions for sustainable establishment.",
  "heroText1": "AFAQ HEALTH is a Moroccan company specializing in the development, import, and marketing of European brands in the fields of nutrition, dietary supplements, and well-being.",
  "heroText2": "We assist European manufacturers and brands in their development on the Moroccan market, combining local market knowledge, regulatory compliance, commercial development, and professional networking.",
  "heroHighlight": "Our role is not limited to distributing products. We build their presence in the market.",
  
  "missionTitle": "OUR MISSION",
  "missionSubtitle": "Making quality European solutions accessible, with a demanding local approach.",
  "missionText1": "Our mission is to select and develop brands that meet high standards of quality, formulation, and compliance, and then create the necessary conditions for their sustainable development in the Moroccan market.",
  "missionText2": "We act as an interface between European manufacturers and the various players in the healthcare chain, ensuring the necessary coordination between the manufacturer's requirements, local market constraints, and the needs of professionals.",
  "chainTitle": "VALUE CHAIN",
  "chain1": "European Manufacturers",
  "chain2": "AFAQ HEALTH",
  "chain3": "DAWA MAGHREB — National Distributor",
  "chain4": "Pharmacies",
  "chain5": "Consumers",
  "accompagnementTitle": "SUPPORT FOR HEALTHCARE PROFESSIONALS",
  "accompagnement1": "AFAQ HEALTH → Healthcare Professionals",
  "accompagnement2": "Consumer Advice and Information",
  "accompagnement3": "Advice provided to consumers is the responsibility of healthcare professionals, as part of their practice.",
  "missionClosing": "Our ambition is to build lasting relationships, based on trust, rigor, and a long-term vision.",

  "expertiseSurtitre": "OUR POSITIONING & EXPERTISE",
  "expertiseTitle": "More than a distributor, a development partner.",
  "expertiseText1": "Accessing a new market is not just about importing a product.",
  "expertiseText2": "It requires understanding the regulatory environment, adapting positioning, preparing the launch, building distribution channels, and gradually developing a presence among healthcare professionals and consumers.",
  "expertiseText3": "This is exactly the role of AFAQ HEALTH.",
  "expertiseSubtitle": "An integrated approach across six areas of expertise",
  "exp1Title": "01 — MARKET ACCESS",
  "exp1Desc": "Potential analysis, positioning, segmentation, and preparation for launch on the Moroccan market.",
  "exp2Title": "02 — REGULATION & COMPLIANCE",
  "exp2Desc": "Coordination of regulatory procedures, preparation and monitoring of product documentation, compliance of materials, and tracking applicable requirements.",
  "exp3Title": "03 — IMPORTATION & AVAILABILITY",
  "exp3Desc": "Organization of import operations and coordination with partners to ensure product availability on the market.",
  "exp4Title": "04 — COMMERCIAL DEVELOPMENT",
  "exp4Desc": "Building and developing distribution channels, supporting the launch, and progressively developing product ranges.",
  "exp5Title": "05 — SUPPORT FOR PROFESSIONALS",
  "exp5Desc": "Providing product information and supporting pharmacists and healthcare professionals in their knowledge and use of our ranges.",
  "exp6Title": "06 — BRAND DEVELOPMENT",
  "exp6Desc": "Positioning, marketing materials, communication, and actions aimed at progressively building a lasting presence in the market.",

  "reseauSurtitre": "OUR NETWORK",
  "reseauTitle": "Building bridges between brands and healthcare professionals",
  "reseauSubtitle": "The development of a health brand relies on the quality of its professional environment.",
  "reseauText": "AFAQ HEALTH works with complementary partners to create a coherent chain, from product availability to consumer access.",
  "net1Title": "EUROPEAN MANUFACTURERS",
  "net1Desc": "Partners selected for the quality of their products, their expertise, and their ability to support the development of their brands in new markets.",
  "net2Title": "DISTRIBUTORS & WHOLESALERS",
  "net2Desc": "Partners ensuring commercial coverage and availability adapted to the market. The national distribution of AFAQ HEALTH products is managed by DAWA MAGHREB, an approved pharmaceutical establishment.",
  "net3Title": "PHARMACIES",
  "net3Desc": "The pharmacy network is an essential point of contact for product availability and consumer access.",
  "net4Title": "HEALTHCARE PROFESSIONALS",
  "net4Desc": "A close relationship allowing for a better presentation of product features and contributing to appropriate consumer information.",
  "reseauClosing": "Our goal: to build a coherent and lasting network around each brand, rather than a simple distribution chain.",

  "engagementsSurtitre": "OUR COMMITMENTS",
  "engagementsTitle": "Excellence. Compliance. Transparency. Responsibility.",
  "eng1Title": "QUALITY",
  "eng1Desc": "We favor brands and products that meet strict criteria for quality, formulation, and traceability.",
  "eng2Title": "COMPLIANCE",
  "eng2Desc": "We pay close attention to the regulatory requirements applicable to each product before it is brought to market and throughout its development.",
  "eng3Title": "PARTNERSHIP",
  "eng3Desc": "We prioritize lasting relationships with our manufacturers, distributors, pharmacists, and healthcare professionals.",
  "eng4Title": "RESPONSIBILITY",
  "eng4Desc": "We ensure our brands are developed with clear, responsible communication that is suited to the regulatory status of each product.",

  "portefeuilleSurtitre": "OUR PORTFOLIO",
  "portefeuilleTitle": "European brands selected for their potential",
  "portefeuilleSubtitle": "AFAQ HEALTH is progressively developing a portfolio of complementary brands in the fields of nutrition, dietary supplements, and well-being.",
  "brand1Title": "SOTYA",
  "brand1Status": "Available in Morocco",
  "brand1Desc": "A Spanish brand of dietary supplements developed around various categories of nutrition and well-being.",
  "brand1Link": "Discover SOTYA",
  "brand2Title": "NATURAMINS KIDS",
  "brand2Status": "Launch scheduled for January 2027",
  "brand2Desc": "A range dedicated to child nutrition and well-being.",
  "brand2Link": "Discover Naturamins Kids",
  "brand3Title": "COLAGENOVA",
  "brand3Status": "Upcoming launch",
  "brand3Desc": "A range specializing in collagen-based solutions, particularly focusing on beauty and mobility.",
  "brand3Link": "Discover Colagenova",
  "allBrandsBtn": "Discover all our brands",

  "ambitionSurtitre": "OUR AMBITION",
  "ambitionTitle": "Building sustainable brands in African markets.",
  "ambitionText1": "Morocco constitutes our development market and our anchor point.",
  "ambitionText2": "Ultimately, AFAQ HEALTH aims to support some of the brands in its portfolio into other French-speaking African markets, taking into account the specific regulatory, commercial, and professional conditions of each country.",
  "ambitionText3": "This ambition is based on a progressive approach: first consolidating brands on the Moroccan market, then building their regional development when the conditions are right.",
  "ambitionHighlight": "Our ambition is not to multiply product lines. It is to build a coherent portfolio of healthcare brands capable of making a lasting impact in their markets."
};

const arContent = {
  "heroSurtitre": "من نحن",
  "heroTitle": "آفاق للصحة، شريك في تطوير العلامات التجارية الصحية",
  "heroSubtitle": "من أوروبا إلى السوق المغربية، نبني ظروفاً لترسيخ مستدام.",
  "heroText1": "آفاق للصحة هي شركة مغربية متخصصة في تطوير واستيراد وتسويق العلامات التجارية الأوروبية في مجالات التغذية والمكملات الغذائية والرفاهية.",
  "heroText2": "نحن نرافق الشركات المصنعة والعلامات التجارية الأوروبية في تطورها داخل السوق المغربية، من خلال الجمع بين معرفة السوق المحلية، والامتثال التنظيمي، والتطوير التجاري، والشبكة المهنية.",
  "heroHighlight": "دورنا لا يقتصر على توزيع المنتجات، بل نبني وجودها في السوق.",
  
  "missionTitle": "مهمتنا",
  "missionSubtitle": "جعل الحلول الأوروبية عالية الجودة في متناول الجميع، بلمسة محلية صارمة.",
  "missionText1": "مهمتنا هي اختيار وتطوير العلامات التجارية التي تلبي معايير عالية الجودة والصياغة والامتثال، ثم تهيئة الظروف اللازمة لتطويرها المستدام في السوق المغربية.",
  "missionText2": "نعمل كحلقة وصل بين المصنعين الأوروبيين ومختلف الفاعلين في سلسلة الصحة، لضمان التنسيق الضروري بين متطلبات المصنع، وقيود السوق المحلية، واحتياجات المهنيين.",
  "chainTitle": "سلسلة القيمة",
  "chain1": "مصنعون أوروبيون",
  "chain2": "آفاق للصحة",
  "chain3": "دواء مغرب — الموزع الوطني",
  "chain4": "الصيدليات",
  "chain5": "المستهلكون",
  "accompagnementTitle": "مرافقة مهنيي الصحة",
  "accompagnement1": "آفاق للصحة ← مهنيو الصحة",
  "accompagnement2": "نصح ومعلومات المستهلكين",
  "accompagnement3": "تعتبر المشورة المقدمة للمستهلكين من مسؤولية مهنيي الصحة، كجزء من ممارساتهم.",
  "missionClosing": "طموحنا هو بناء علاقات مستدامة، قائمة على الثقة، والصرامة، والرؤية طويلة المدى.",

  "expertiseSurtitre": "موقعنا وخبرتنا",
  "expertiseTitle": "أكثر من مجرد موزع، نحن شريك تطوير.",
  "expertiseText1": "الوصول إلى سوق جديد لا يقتصر على استيراد المنتج.",
  "expertiseText2": "بل يتطلب فهم البيئة التنظيمية، وتكييف التموضع، والتحضير للإطلاق، وبناء قنوات التوزيع، وتطوير التواجد تدريجياً لدى مهنيي الصحة والمستهلكين.",
  "expertiseText3": "هذا هو تحديداً دور آفاق للصحة.",
  "expertiseSubtitle": "نهج متكامل عبر ستة مجالات خبرة",
  "exp1Title": "01 — الوصول إلى السوق",
  "exp1Desc": "تحليل الإمكانيات، التموضع، التقسيم، والتحضير للإطلاق في السوق المغربية.",
  "exp2Title": "02 — التنظيم والامتثال",
  "exp2Desc": "تنسيق الإجراءات التنظيمية، وإعداد ومتابعة وثائق المنتج، ومطابقة المواد التسويقية، ومتابعة المتطلبات السارية.",
  "exp3Title": "03 — الاستيراد والتوفير",
  "exp3Desc": "تنظيم عمليات الاستيراد والتنسيق مع الشركاء لضمان توافر المنتجات في السوق.",
  "exp4Title": "04 — التطوير التجاري",
  "exp4Desc": "بناء وتطوير قنوات التوزيع، ومواكبة إطلاق المنتجات، وتطوير المجموعات بشكل تدريجي.",
  "exp5Title": "05 — مرافقة المهنيين",
  "exp5Desc": "توفير معلومات المنتجات ومواكبة الصيادلة ومهنيي الصحة في معرفة المجموعات وكيفية استخدامها.",
  "exp6Title": "06 — تطوير العلامة التجارية",
  "exp6Desc": "التموضع، والمواد التسويقية، والتواصل، والإجراءات الهادفة إلى بناء حضور مستدام تدريجياً في السوق.",

  "reseauSurtitre": "شبكتنا",
  "reseauTitle": "بناء جسور بين العلامات التجارية ومهنيي الصحة",
  "reseauSubtitle": "تطوير العلامة التجارية الصحية يعتمد على جودة بيئتها المهنية.",
  "reseauText": "تعمل آفاق للصحة مع شركاء متكاملين لإنشاء سلسلة متماسكة، من توافر المنتجات وصولاً إلى المستهلكين.",
  "net1Title": "مصنعون أوروبيون",
  "net1Desc": "شركاء تم اختيارهم بناءً على جودة منتجاتهم، وخبراتهم، وقدرتهم على دعم تطوير علاماتهم التجارية في أسواق جديدة.",
  "net2Title": "الموزعون وتجار الجملة",
  "net2Desc": "شركاء يضمنون التغطية التجارية والتوافر المناسب للسوق. يتم إدارة التوزيع الوطني لمنتجات آفاق للصحة من قبل دواء مغرب، وهي مؤسسة صيدلانية معتمدة.",
  "net3Title": "الصيدليات",
  "net3Desc": "تعد شبكة الصيدليات نقطة اتصال أساسية لتوفر المنتجات ووصول المستهلكين إليها.",
  "net4Title": "مهنيو الصحة",
  "net4Desc": "علاقة قريبة تتيح تقديم خصائص المنتجات بشكل أفضل وتساهم في تزويد المستهلكين بمعلومات دقيقة.",
  "reseauClosing": "هدفنا: بناء شبكة متماسكة ومستدامة حول كل علامة تجارية، بدلاً من مجرد سلسلة توزيع.",

  "engagementsSurtitre": "التزاماتنا",
  "engagementsTitle": "التميز. الامتثال. الشفافية. المسؤولية.",
  "eng1Title": "الجودة",
  "eng1Desc": "نفضل العلامات التجارية والمنتجات التي تلبي معايير صارمة للجودة والصياغة والتتبع.",
  "eng2Title": "الامتثال",
  "eng2Desc": "نولي اهتماماً خاصاً بالمتطلبات التنظيمية المطبقة على كل منتج قبل طرحه في السوق وطوال فترة تطويره.",
  "eng3Title": "الشراكة",
  "eng3Desc": "نعطي الأولوية للعلاقات الدائمة مع المصنعين والموزعين والصيادلة ومهنيي الصحة.",
  "eng4Title": "المسؤولية",
  "eng4Desc": "نحرص على تطوير علاماتنا التجارية من خلال تواصل واضح ومسؤول ومتناسب مع الوضع التنظيمي لكل منتج.",

  "portefeuilleSurtitre": "محفظتنا",
  "portefeuilleTitle": "علامات تجارية أوروبية تم اختيارها لإمكانياتها",
  "portefeuilleSubtitle": "تقوم آفاق للصحة بتطوير محفظة من العلامات التجارية المتكاملة تدريجياً في مجالات التغذية والمكملات الغذائية والرفاهية.",
  "brand1Title": "صوتيا (SOTYA)",
  "brand1Status": "متوفر في المغرب",
  "brand1Desc": "علامة تجارية إسبانية للمكملات الغذائية، تم تطويرها حول فئات مختلفة من التغذية والرفاهية.",
  "brand1Link": "اكتشف صوتيا",
  "brand2Title": "ناتورامينز كيدز (NATURAMINS KIDS)",
  "brand2Status": "من المقرر إطلاقها في يناير 2027",
  "brand2Desc": "مجموعة مخصصة لتغذية الأطفال ورفاهيتهم.",
  "brand2Link": "اكتشف ناتورامينز كيدز",
  "brand3Title": "كولاجينوفا (COLAGENOVA)",
  "brand3Status": "قريباً",
  "brand3Desc": "مجموعة متخصصة في الحلول القائمة على الكولاجين، خاصة فيما يتعلق بالجمال والمرونة.",
  "brand3Link": "اكتشف كولاجينوفا",
  "allBrandsBtn": "اكتشف جميع علاماتنا التجارية",

  "ambitionSurtitre": "طموحنا",
  "ambitionTitle": "بناء علامات تجارية مستدامة في الأسواق الأفريقية.",
  "ambitionText1": "المغرب يمثل سوق التنمية ونقطة ارتكازنا.",
  "ambitionText2": "في النهاية، تهدف آفاق للصحة إلى مرافقة بعض العلامات التجارية في محفظتها نحو أسواق أفريقية أخرى ناطقة بالفرنسية، مع مراعاة الخصائص التنظيمية والتجارية والمهنية الخاصة بكل دولة.",
  "ambitionText3": "يعتمد هذا الطموح على نهج تدريجي: أولاً تعزيز العلامات التجارية في السوق المغربية، ثم بناء تطويرها الإقليمي عندما تتوفر الظروف المناسبة.",
  "ambitionHighlight": "طموحنا ليس مضاعفة عدد المنتجات، بل بناء محفظة متماسكة من العلامات التجارية الصحية، قادرة على إحداث أثر مستدام في أسواقها."
};

['fr', 'en', 'ar'].forEach(lang => {
  const p = path.join(__dirname, 'messages', `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(p, 'utf8'));
  
  if(lang === 'fr') data.AboutPage = frContent;
  if(lang === 'en') data.AboutPage = enContent;
  if(lang === 'ar') data.AboutPage = arContent;

  fs.writeFileSync(p, JSON.stringify(data, null, 2));
});
