/**
 * Product data extracted from the official SOTYA Catalogue 2026
 * Organized into Universes / Needs and Brands
 */

export interface Product {
  id: string;
  name: string;
  brand: string;
  categories: string[];
  imagePath: string;
  labelImagePath?: string;
  description: string;
  longDescription?: string;
  composition?: string;
  howToUse?: string;
  warning?: string;
  benefits: string[];
  dosage: string;
  duration: string;
  format: string;
  certifications: string[];
}

export const PRODUCT_CATEGORIES = [
  'Énergie & Vitalité',
  'Stress & Sommeil',
  'Immunité & Défenses',
  'Beauté',
  'Articulations & Mobilité',
  'Nutrition pédiatrique',
  'Santé Spécifique'
];

export const PRODUCT_BRANDS = [
  'SOTYA',
  'NATURAMINS KIDS',
  'COLAGENOVA'
];

const WARNING_TEXT = "Ne pas dépasser la dose journalière recommandée. Les compléments alimentaires ne doivent pas être utilisés comme substituts d'un régime alimentaire varié et équilibré et d'un mode de vie sain. Tenir hors de portée des enfants.";

export const products: Product[] = [
  // ─── SOTYA ────────────────────────
  {
    id: 'bisglycinate-magnesium',
    name: 'Bisglycinate de Magnésium',
    brand: 'SOTYA',
    categories: ['Stress & Sommeil', 'Énergie & Vitalité'],
    imagePath: '/images/products/magnesium.jpeg',
    labelImagePath: '/images/labels/bisglycinate-magnesium.png',
    description: 'Complément alimentaire à base de magnésium, zinc et vitamine D3. Le magnésium contribue à réduire la fatigue et au fonctionnement normal du système nerveux et musculaire.',
    longDescription: "Cette formule associe du magnésium sous forme de bisglycinate à du zinc et à la vitamine D3. Le magnésium contribue à réduire la fatigue et au fonctionnement normal du système nerveux et musculaire, tandis que le zinc et la vitamine D participent au fonctionnement normal de l'organisme.\nUne formule pensée pour accompagner les besoins quotidiens en magnésium, notamment lors des périodes de fatigue ou lorsque les besoins nutritionnels sont accrus.",
    composition: "Pour 3 gélules : magnésium 327 mg (87 % VNR), zinc 15 mg (150 % VNR), vitamine D 5 µg (100 % VNR).",
    howToUse: "Prendre 3 gélules par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Stress et fatigue', 'Détente et sommeil', 'Système nerveux'],
    dosage: '3 gélules par jour',
    duration: '33 jours',
    format: '100 gélules végétales de 750mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'complexe-vitamines-b',
    name: 'Complexe de Vitamines B',
    brand: 'SOTYA',
    categories: ['Énergie & Vitalité'],
    imagePath: '/images/products/vitamines-b.jpeg',
    labelImagePath: '/images/labels/complexe-vitamines-b.png',
    description: 'Complément alimentaire à base de vitamines du groupe B, choline et inositol. Les vitamines B2, B3, B5, B6 et B12 contribuent à réduire la fatigue.',
    longDescription: "Une formule complète qui réunit les principales vitamines du groupe B, associées à la choline et à l'inositol. Les vitamines B2, B3, B5, B6 et B12 contribuent à réduire la fatigue, tandis que les vitamines B1, B6 et B12 contribuent au fonctionnement normal du système nerveux.\nUne formule quotidienne destinée à accompagner les besoins nutritionnels liés à la vitalité, à l'énergie et au bon fonctionnement du système nerveux.",
    composition: "Pour 1 gélule : vitamine B1 1,1 mg, vitamine B2 1,4 mg (100 % VNR), vitamine B3 16 mg (100 % VNR), vitamine B6 5 mg, vitamine B5 6 mg (100 % VNR), biotine 50 µg (100 % VNR), acide folique 200 µg (100 % VNR), vitamine B12 2,5 µg (100 % VNR), choline 50 mg, inositol 50 mg.",
    howToUse: "Prendre 1 gélule par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Énergie et vitalité', 'Performances mentales'],
    dosage: '1 gélule par jour',
    duration: '60 jours',
    format: '60 gélules végétales de 620mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'complexe-melatonine',
    name: 'Complexe de Mélatonine',
    brand: 'SOTYA',
    categories: ['Stress & Sommeil'],
    imagePath: '/images/products/melatonine.jpeg',
    labelImagePath: '/images/labels/complexe-melatonine.png',
    description: 'Complément alimentaire à base de vitamines du groupe B, choline et inositol. Les vitamines B2, B3, B5, B6 et B12 contribuent à réduire la fatigue.',
    longDescription: "Cette formule associe la mélatonine au magnésium, au L-tryptophane et à la vitamine B6. La mélatonine contribue à réduire le temps nécessaire à l'endormissement lorsqu'elle est consommée peu avant le coucher, tandis que le magnésium et la vitamine B6 participent au fonctionnement normal du système nerveux.\nUne formule conçue pour accompagner la routine du soir et les besoins liés à l'endormissement.",
    composition: "Pour 2 gélules : magnésium 112,5 mg (30 % VNR), L-tryptophane 100 mg, vitamine B6 6 mg (100 % VNR), mélatonine 1,8 mg.",
    howToUse: "Prendre 2 gélules peu avant le coucher.",
    warning: WARNING_TEXT,
    benefits: ['Endormissement rapide', 'Détente mentale', 'Décalage horaire'],
    dosage: '2 gélules par jour',
    duration: '30 jours',
    format: '60 gélules végétales de 550mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'melatonine',
    name: 'Mélatonine',
    brand: 'SOTYA',
    categories: ['Stress & Sommeil'],
    imagePath: '/images/products/melatonine.jpeg',
    description: 'Complément alimentaire à base de mélatonine, mélisse, passiflore et tilleul. La mélatonine contribue notamment à atténuer la sensation subjective de décalage horaire lorsqu\'elle est consommée peu avant le coucher.',
    longDescription: "Cette formule associe la mélatonine à trois plantes traditionnellement utilisées dans les préparations du soir : la mélisse, la passiflore et le tilleul. La mélatonine contribue notamment à atténuer la sensation subjective de décalage horaire lorsqu'elle est consommée peu avant le coucher.\nUne formule particulièrement adaptée aux routines du soir et aux situations impliquant un changement de rythme ou de fuseau horaire.",
    composition: "Pour 2 gélules : extrait de mélisse 400 mg (acide rosmarinique 10 mg), extrait de passiflore 400 mg (flavonoïdes 16 mg), extrait de tilleul 200 mg (flavonoïdes 2 mg), mélatonine 1,8 mg.",
    howToUse: "Prendre 2 gélules peu avant le coucher.",
    warning: WARNING_TEXT,
    benefits: ['Relaxation et sommeil naturel', 'Réduction de la fatigue'],
    dosage: '2 gélules par jour',
    duration: '30 jours',
    format: '60 gélules végétales de 650mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha',
    brand: 'SOTYA',
    categories: ['Stress & Sommeil'],
    imagePath: '/images/products/ashwaganda.jpeg',
    labelImagePath: '/images/labels/ashwagandha.png',
    description: 'Complément alimentaire à base d\'extrait d\'Ashwagandha, vitamine C et zinc. La vitamine C contribue à réduire la fatigue et au fonctionnement normal du système nerveux.',
    longDescription: "Cette formule associe un extrait de racine d'Ashwagandha à de la vitamine C et du zinc. L'Ashwagandha est une plante traditionnellement utilisée dans la tradition ayurvédique, tandis que la vitamine C contribue à réduire la fatigue et au fonctionnement normal du système nerveux et que le zinc contribue au fonctionnement normal du système immunitaire.\nUne association entre extrait végétal et micronutriments pour accompagner les besoins de l'organisme au quotidien, notamment lors des périodes de fatigue et de sollicitation.",
    composition: "Pour 1 gélule : extrait d'Ashwagandha 300 mg, vitamine C 80 mg (100 % VNR), zinc 10 mg (100 % VNR).",
    howToUse: "Prendre 1 gélule par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Relaxation et bien-être', 'Défenses naturelles'],
    dosage: '1 gélule par jour',
    duration: '60 jours',
    format: '60 gélules végétales de 570mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'complexe-vitamine-c',
    name: 'Complexe de Vitamine C',
    brand: 'SOTYA',
    categories: ['Immunité & Défenses', 'Énergie & Vitalité'],
    imagePath: '/images/products/vitamine-c.jpeg',
    labelImagePath: '/images/labels/complexe-vitamine-c.png',
    description: 'Complément alimentaire à base de vitamine C, acérola, églantier et bioflavonoïdes. La vitamine C contribue au fonctionnement normal du système immunitaire et à réduire la fatigue.',
    longDescription: "Cette formule associe de la vitamine C à des extraits d'acérola et d'églantier ainsi qu'à des bioflavonoïdes d'agrumes. La vitamine C contribue au fonctionnement normal du système immunitaire et à réduire la fatigue.\nUne formule complète qui associe vitamine C et ingrédients d'origine végétale pour accompagner les besoins quotidiens en période de fatigue ou lors des changements de saison.",
    composition: "Pour 1 comprimé : vitamine C totale 80 mg (100 % VNR), flavonoïdes citriques 279 mg, sinéfrine 16,7 mg, fibre de bambou 188 mg, extrait d'églantier 56 mg, extrait d'acérola 47 mg, acide L-ascorbique 40 mg.",
    howToUse: "Prendre 1 comprimé par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Anti-fatigue', 'Défenses naturelles', 'Énergie et vitalité', 'Circulation veineuse'],
    dosage: '1 comprimé par jour',
    duration: '90 jours',
    format: '90 comprimés de 1g',
    certifications: ['Sans gluten'],
  },
  {
    id: 'complexe-propolis-forte',
    name: 'Complexe de Propolis Forte',
    brand: 'SOTYA',
    categories: ['Immunité & Défenses'],
    imagePath: '/images/products/propolis.jpeg',
    labelImagePath: '/images/labels/complexe-propolis-forte.png',
    description: 'Complément alimentaire à base de propolis, échinacée, thym, miel et vitamine C. La vitamine C contribue au fonctionnement normal du système immunitaire.',
    longDescription: "Cette formule associe propolis, échinacée, thym, miel et vitamine C. La vitamine C contribue au fonctionnement normal du système immunitaire, tandis que la propolis, le thym et l'échinacée sont traditionnellement utilisés dans les préparations destinées au confort des voies respiratoires.\nPrésentée sous forme de comprimés à croquer, cette formule associe ainsi plusieurs ingrédients d'origine naturelle dans une utilisation pratique au quotidien.",
    composition: "Pour 4 comprimés : vitamine C 80 mg (100 % VNR), extrait de propolis 377 mg (galangine 37,7 mg), miel en poudre 94 mg, citron en poudre 47 mg, extrait de thym 44 mg (flavonoïdes 2,6 mg), extrait d'échinacée 45 mg (polyphénols 1,8 mg).",
    howToUse: "Prendre 4 comprimés par jour.",
    warning: WARNING_TEXT,
    benefits: ['Défenses naturelles', 'Voies respiratoires', 'Confort respiratoire'],
    dosage: '4 comprimés par jour',
    duration: '25 jours',
    format: '100 comprimés de 800mg',
    certifications: ['Sans gluten'],
  },
  {
    id: 'complexe-omega-369',
    name: 'Complexe d\'Oméga 3, 6, 9',
    brand: 'SOTYA',
    categories: ['Beauté', 'Articulations & Mobilité', 'Santé Spécifique'],
    imagePath: '/images/products/omegaa.jpeg',
    labelImagePath: '/images/labels/complexe-omega-369.png',
    description: 'Complément alimentaire à base de Huile de poisson, Huile de lin, Huile d\'onagre et Vitamine E.',
    longDescription: "Cette formule réunit trois sources d'acides gras : l'huile de poisson, l'huile de lin et l'huile d'onagre. Elle apporte notamment des oméga-3 issus de l'huile de poisson et du lin, des oméga-6 issus de l'onagre et du lin, ainsi que des oméga-9. La formule est complétée par de la vitamine E.\nUne association de sources marines et végétales pour apporter différentes familles d'acides gras dans une même formule.",
    composition: "Pour 3 perles : huile de poisson 996 mg (EPA 180 mg, DHA 120 mg), huile de lin 996 mg (ALA 648 mg, acide linoléique 240 mg, acide oléique 240 mg), huile d'onagre 996 mg (GLA 100 mg), vitamine E 7,5 mg (62,5 % VNR).",
    howToUse: "Prendre 3 perles par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Santé cardiovasculaire', 'Cholestérol équilibré', 'Peau et articulations'],
    dosage: '3 perles par jour',
    duration: '16 jours',
    format: '50 perles de 1400mg',
    certifications: ['Sans gluten'],
  },
  {
    id: 'prostal',
    name: 'Prostal',
    brand: 'SOTYA',
    categories: ['Santé Spécifique'],
    imagePath: '/images/products/prostal.jpeg',
    labelImagePath: '/images/labels/prostal.png',
    description: 'Complément alimentaire à base d\'Extraits de citrouille, trèfle rouge, saw palmetto, thé vert, romarin, lycopène et zinc. Contient de la caféine.',
    longDescription: "Cette formule associe plusieurs extraits végétaux — saw palmetto, graines de courge, trèfle rouge, thé vert et romarin — à du zinc, du lycopène et de la quercétine. Le zinc contribue au maintien d'un taux normal de testostérone dans le sang.\nUne formule complète destinée à accompagner les besoins nutritionnels spécifiques de l'homme, avec une association d'extraits végétaux et de micronutriments.",
    composition: "Pour 1 gélule : extrait de thé vert 170 mg (polyphénols 85 mg, catéchines 51 mg, EGCG 25,5 mg, caféine 12 mg), extrait de citrouille 83 mg, extrait de trèfle rouge 83 mg (isoflavones 6,6 mg), extrait de saw palmetto 83 mg (acides gras 21 mg), extrait de romarin 13 mg, zinc 10 mg (100 % VNR), quercétine 10 mg, lycopène 0,5 mg.",
    howToUse: "Prendre 1 gélule par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Confort urinaire masculin', 'Santé prostatique'],
    dosage: '1 gélule par jour',
    duration: '30 jours',
    format: '30 gélules végétales de 650mg',
    certifications: [],
  },
  {
    id: 'huile-onagre',
    name: 'Huile d\'Onagre',
    brand: 'SOTYA',
    categories: ['Beauté', 'Santé Spécifique'],
    imagePath: '/images/products/onagre.jpeg',
    labelImagePath: '/images/labels/huile-onagre.png',
    description: 'Complément alimentaire à base d\'huile de graines d\'onagre, naturellement riche en acide gamma-linolénique (GLA), et de vitamine E. La vitamine E contribue à protéger les cellules contre le stress oxydatif.',
    longDescription: "Cette formule apporte de l'huile de graines d'onagre naturellement riche en acide gamma-linolénique (GLA), un acide gras de la famille des oméga-6. Elle est complétée par de la vitamine E, qui contribue à protéger les cellules contre le stress oxydatif.\nUne formule simple et ciblée, basée sur une huile végétale reconnue pour sa richesse en GLA et adaptée à une utilisation quotidienne.",
    composition: "Pour 1 à 2 perles : huile d'onagre 2 000 mg, GLA 200 mg, vitamine E 10 mg (83 % VNR).",
    howToUse: "Prendre 1 à 2 perles par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Équilibre hormonal prénatal', 'Santé gynécologique', 'Peau et articulations'],
    dosage: '1 à 2 perles par jour',
    duration: '25 jours',
    format: '50 perles de 1405mg',
    certifications: ['Sans gluten'],
  },
  {
    id: 'charbon-actif-probiotiques',
    name: 'Charbon Actif avec Probiotiques',
    brand: 'SOTYA',
    categories: ['Santé Spécifique'],
    imagePath: '/images/products/charbon.jpeg',
    labelImagePath: '/images/labels/charbon-actif-probiotiques.png',
    description: 'Complément alimentaire à base de charbon végétal actif, probiotiques et prébiotiques. Le charbon végétal actif contribue à réduire les flatulences excessives après les repas.',
    longDescription: "Cette formule associe du charbon végétal actif à trois souches de probiotiques — Bifidobacterium longum, Lactobacillus plantarum et Lactobacillus reuteri — ainsi qu'à des fructo-oligosaccharides (FOS), de l'anis étoilé et du fenouil.\nLe charbon végétal actif contribue à réduire les flatulences excessives après les repas. L'association de probiotiques, de fibres prébiotiques et d'extraits végétaux complète cette formule dédiée au confort digestif.",
    composition: "Pour 6 gélules : charbon végétal 1 010 mg, extrait d'anis 506 mg, fructo-oligosaccharides 506 mg, extrait de fenouil 202 mg, probiotiques 40 mg (B. longum 2 × 10⁸ UFC, L. plantarum 1 × 10⁸ UFC, L. reuteri 1 × 10⁸ UFC).",
    howToUse: "Prendre 6 gélules par jour selon les indications du produit.",
    warning: WARNING_TEXT,
    benefits: ['Santé gastro-intestinale', 'Flore digestive', 'Bien-être digestif'],
    dosage: '6 gélules par jour',
    duration: '15 jours',
    format: '90 gélules végétales de 550mg',
    certifications: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'collagene',
    name: 'Collagène',
    brand: 'SOTYA',
    categories: ['Beauté', 'Articulations & Mobilité'],
    imagePath: '/images/products/collagene.jpeg',
    labelImagePath: '/images/labels/collagene.png',
    description: 'Complément alimentaire à base de collagène hydrolysé, silicium, magnésium et vitamines C et D. La vitamine C contribue à la formation normale de collagène pour assurer la fonction normale des os, des cartilages et de la peau. ',
    longDescription: "Cette formule associe du collagène hydrolysé au silicium organique, au magnésium et aux vitamines C et D. La vitamine C contribue à la formation normale de collagène pour assurer la fonction normale des os, des cartilages et de la peau, tandis que la vitamine D contribue au maintien d'une ossature normale.\nUne formule qui associe collagène et micronutriments pour répondre à la fois aux besoins liés à la structure des tissus et au maintien d'une peau et d'une ossature normales.",
    composition: "Pour 4 comprimés : collagène 2 100 mg, vitamine C 80 mg (100 % VNR), vitamine D3 5 µg (100 % VNR), magnésium 346 mg (93 % VNR), acide orthosilicique 120 mg (silicium 30 mg).",
    howToUse: "Prendre 4 comprimés par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Renforcement des cheveux', 'Élasticité de la peau', 'Os et articulations', 'Renouvellement des tissus'],
    dosage: '4 comprimés par jour',
    duration: '22 jours',
    format: '90 comprimés de 1,3g',
    certifications: ['Sans gluten'],
  },
  {
    id: 'peau-cheveux-ongles',
    name: 'Peau, Cheveux et Ongles',
    brand: 'SOTYA',
    categories: ['Beauté'],
    imagePath: '/images/products/peau.jpeg',
    labelImagePath: '/images/labels/peau-cheveux-ongles.png',
    description: 'Complément alimentaire à base de levure de bière, collagène, prêle, vitamines et minéraux. La biotine et le zinc contribuent au maintien de cheveux et d\'une peau normaux, tandis que le zinc et le sélénium contribuent au maintien d\'ongles normaux.',
    longDescription: "Cette formule associe levure de bière, collagène hydrolysé, extrait de prêle et taurine à un ensemble de vitamines et minéraux. La biotine et le zinc contribuent au maintien de cheveux et d'une peau normaux, tandis que le zinc et le sélénium contribuent au maintien d'ongles normaux.\nUne formule complète dédiée à la beauté de la peau, des cheveux et des ongles, réunissant vitamines, minéraux et ingrédients d'origine naturelle.",
    composition: "Pour 2 gélules : levure de bière 164 mg, collagène 140 mg, extrait de prêle 140 mg, vitamine C 80 mg (100 % VNR), vitamine E 12 mg (100 % VNR), zinc 10 mg (100 % VNR), silice 10 mg, taurine 48 mg, vitamine A 800 µg (100 % VNR), vitamine D 5 µg (100 % VNR), vitamine B1 1,1 mg, vitamine B2 1,4 mg, vitamine B3 16 mg, vitamine B5 6 mg, vitamine B6 1,4 mg, acide folique 200 µg, vitamine B12 2,5 µg, biotine 50 µg (100 % VNR), fer 14 mg (100 % VNR), sélénium 55 µg (100 % VNR).",
    howToUse: "Prendre 2 gélules par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Croissance des cheveux', 'Élasticité de la peau', 'Ongles forts'],
    dosage: '2 gélules par jour',
    duration: '30 jours',
    format: '60 gélules de 522mg',
    certifications: ['Sans gluten'],
  },
  {
    id: 'multivitamines-mineraux',
    name: 'Multivitamines & Minéraux',
    brand: 'SOTYA',
    categories: ['Énergie & Vitalité'],
    imagePath: '/images/products/multivitamines.jpeg',
    labelImagePath: '/images/labels/multivitamines-mineraux.png',
    description: 'Complément alimentaire à base de vitamines, minéraux, coenzyme Q10, lutéine et lycopène. Les vitamines B2, B3, B5 et C, ainsi que le fer et le magnésium, contribuent à réduire la fatigue.',
    longDescription: "Cette formule associe un ensemble de vitamines et de minéraux à de la lutéine, de la coenzyme Q10 et du lycopène. Les vitamines B2, B3, B5 et C, ainsi que le fer et le magnésium, contribuent à réduire la fatigue.\nUne formule complète destinée à accompagner les besoins nutritionnels quotidiens et à contribuer au maintien de la vitalité, notamment lorsque l'organisme est particulièrement sollicité.",
    composition: "Pour 1 gélule : vitamine A 800 µg (100 % VNR), vitamine C 80 mg (100 % VNR), vitamine D 5 µg (100 % VNR), vitamine E 12 mg (100 % VNR), vitamine K 75 µg (100 % VNR), vitamine B1 1,1 mg, vitamine B2 1,4 mg, vitamine B3 16 mg, vitamine B5 6 mg, vitamine B6 1,4 mg, biotine 49 µg (98 % VNR), acide folique 200 µg, vitamine B12 2,5 µg, magnésium 126 mg (34 % VNR), fer 7,3 mg (52 % VNR), zinc 4,2 mg (42 % VNR), cuivre 420 µg (42 % VNR), manganèse 0,8 mg (42 % VNR), sélénium 22 µg (41 % VNR), chrome 18,5 µg (46 % VNR), iode 33 µg (22 % VNR), coenzyme Q10 30 mg, lutéine 1,5 mg, lycopène 1,5 mg.",
    howToUse: "Prendre 1 gélule par jour avec un grand verre d'eau.",
    warning: WARNING_TEXT,
    benefits: ['Santé générale et énergie', 'Santé oculaire', 'Santé cardiaque'],
    dosage: '1 gélule par jour',
    duration: '60 jours',
    format: '60 gélules végétales de 820mg',
    certifications: ['Vegan', 'Sans gluten'],
  },

  // ─── NATURAMINS KIDS ────────────────────────
  {
    id: 'naturamins-kids-multi',
    name: 'Multivitamines Gummies',
    brand: 'NATURAMINS KIDS',
    categories: ['Nutrition pédiatrique', 'Immunité & Défenses'],
    imagePath: '/images/unsplash/comp/Gemini_Generated_Image_1tkniv1tkniv1tkn.jpg', // placeholder
    description: 'Complément alimentaire à base de 11 vitamines, zinc et iode. Forme gomme.',
    benefits: ['Défenses naturelles', 'Croissance saine', 'Énergie'],
    dosage: '2 gommes par jour',
    duration: '30 jours',
    format: '60 gommes fruitées',
    certifications: ['Sans gluten', 'Sans sucres ajoutés'],
  },

  // ─── COLAGENOVA ────────────────────────
  {
    id: 'colagenova-marine',
    name: 'Marine Beauty',
    brand: 'COLAGENOVA',
    categories: ['Beauté', 'Articulations & Mobilité'],
    imagePath: '/images/unsplash/welness/capture_welness_2.png', // placeholder
    description: 'Complément alimentaire à base de Peptides de collagène marin pur, Acide hyaluronique et Vitamine C.',
    benefits: ['Hydratation de la peau', 'Réduction des rides', 'Souplesse articulaire'],
    dosage: '2 dosettes par jour',
    duration: '21 jours',
    format: 'Poudre 275g (Saveur Vanille)',
    certifications: ['Sans gluten', 'Arômes naturels'],
  },
];
